### ISSUE TITLE
Suggestion PSVR2

### ISSUE THREAD

**Issue by myszmad** [little-core-labs/handbrake-presets#1]
The PSVR2 app could have the ability to read video covers contained within a file, as well as the ability to view jpg files.

**Comment by greenmatthew** [comment]
Sorry for not responding sooner. My repo notification settings were not correctly set.

This repo is for HandBrake encoding presets, not suggestions for improvements of our apps. 

We plan on implementing proper thumbnails for sideloading and RSS, as well as the ability to view images for PSVR2.

If you have any other suggestions please reach out on our [Discord server](https://discord.com/invite/radtv) or email our support [`support@radtv.com`](mailto:support@radtv.com).

Cheers,
Matthew
